/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RattrapageRouteImport } from './routes/rattrapage'
import { Route as ProfesseurRouteImport } from './routes/professeur'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as EleveRouteImport } from './routes/eleve'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RattrapageRoute = RattrapageRouteImport.update({
  id: '/rattrapage',
  path: '/rattrapage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseurRoute = ProfesseurRouteImport.update({
  id: '/professeur',
  path: '/professeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const EleveRoute = EleveRouteImport.update({
  id: '/eleve',
  path: '/eleve',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/eleve': typeof EleveRoute
  '/parent': typeof ParentRoute
  '/professeur': typeof ProfesseurRoute
  '/rattrapage': typeof RattrapageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/eleve': typeof EleveRoute
  '/parent': typeof ParentRoute
  '/professeur': typeof ProfesseurRoute
  '/rattrapage': typeof RattrapageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/eleve': typeof EleveRoute
  '/parent': typeof ParentRoute
  '/professeur': typeof ProfesseurRoute
  '/rattrapage': typeof RattrapageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/eleve'
    | '/parent'
    | '/professeur'
    | '/rattrapage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/eleve' | '/parent' | '/professeur' | '/rattrapage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/eleve'
    | '/parent'
    | '/professeur'
    | '/rattrapage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EleveRoute: typeof EleveRoute
  ParentRoute: typeof ParentRoute
  ProfesseurRoute: typeof ProfesseurRoute
  RattrapageRoute: typeof RattrapageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rattrapage': {
      id: '/rattrapage'
      path: '/rattrapage'
      fullPath: '/rattrapage'
      preLoaderRoute: typeof RattrapageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeur': {
      id: '/professeur'
      path: '/professeur'
      fullPath: '/professeur'
      preLoaderRoute: typeof ProfesseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleve': {
      id: '/eleve'
      path: '/eleve'
      fullPath: '/eleve'
      preLoaderRoute: typeof EleveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EleveRoute: EleveRoute,
  ParentRoute: ParentRoute,
  ProfesseurRoute: ProfesseurRoute,
  RattrapageRoute: RattrapageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
