-- Karanta foundation: multi-organization access, server-controlled roles and
-- tenant-scoped legacy learning data. Designed for a fresh Diakspora project
-- while remaining safe to apply to the historical prototype database.

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA private TO authenticated;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS preferred_name text,
  ADD COLUMN IF NOT EXISTS avatar_url text,
  ADD COLUMN IF NOT EXISTS locale text NOT NULL DEFAULT 'fr',
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 120),
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'suspended', 'archived')),
  logo_url text,
  primary_color text NOT NULL DEFAULT '#1E5631'
    CHECK (primary_color ~ '^#[0-9A-Fa-f]{6}$'),
  accent_color text NOT NULL DEFAULT '#C9932F'
    CHECK (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  default_locale text NOT NULL DEFAULT 'fr',
  enabled_locales text[] NOT NULL DEFAULT ARRAY['fr']::text[],
  custom_domain text UNIQUE,
  feature_flags jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.organization_memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (
    role IN (
      'owner',
      'admin',
      'technician',
      'pedagogical_manager',
      'teacher',
      'class_manager',
      'parent',
      'learner'
    )
  ),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('invited', 'active', 'suspended')),
  is_default boolean NOT NULL DEFAULT false,
  invited_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, user_id, role)
);

CREATE UNIQUE INDEX IF NOT EXISTS organization_memberships_one_default_per_user
  ON public.organization_memberships (user_id)
  WHERE is_default AND status = 'active';

CREATE INDEX IF NOT EXISTS organization_memberships_organization_user_idx
  ON public.organization_memberships (organization_id, user_id)
  WHERE status = 'active';

CREATE TABLE IF NOT EXISTS public.family_relationships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  parent_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  learner_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  relationship text NOT NULL DEFAULT 'guardian'
    CHECK (relationship IN ('parent', 'guardian')),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('pending', 'active', 'revoked')),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (parent_user_id <> learner_user_id),
  UNIQUE (organization_id, parent_user_id, learner_user_id)
);

CREATE TABLE IF NOT EXISTS public.platform_administrators (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'platform_admin'
    CHECK (role IN ('platform_owner', 'platform_admin', 'platform_support')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_logs_organization_created_idx
  ON public.audit_logs (organization_id, created_at DESC);

CREATE OR REPLACE FUNCTION private.is_platform_administrator()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.platform_administrators AS administrator
    WHERE administrator.user_id = (SELECT auth.uid())
  );
$$;

CREATE OR REPLACE FUNCTION private.is_organization_member(p_organization_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT auth.uid()) IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.organization_memberships AS membership
      WHERE membership.organization_id = p_organization_id
        AND membership.user_id = (SELECT auth.uid())
        AND membership.status = 'active'
    );
$$;

CREATE OR REPLACE FUNCTION private.has_organization_role(
  p_organization_id uuid,
  p_roles text[]
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT auth.uid()) IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.organization_memberships AS membership
      WHERE membership.organization_id = p_organization_id
        AND membership.user_id = (SELECT auth.uid())
        AND membership.status = 'active'
        AND membership.role = ANY (p_roles)
    );
$$;

CREATE OR REPLACE FUNCTION private.is_linked_parent(
  p_organization_id uuid,
  p_learner_user_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT auth.uid()) IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.family_relationships AS relationship
      WHERE relationship.organization_id = p_organization_id
        AND relationship.parent_user_id = (SELECT auth.uid())
        AND relationship.learner_user_id = p_learner_user_id
        AND relationship.status = 'active'
    );
$$;

REVOKE ALL ON FUNCTION private.is_platform_administrator() FROM PUBLIC;
REVOKE ALL ON FUNCTION private.is_organization_member(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION private.has_organization_role(uuid, text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION private.is_linked_parent(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION private.is_platform_administrator() TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_organization_member(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.has_organization_role(uuid, text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_linked_parent(uuid, uuid) TO authenticated;

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.family_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_administrators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.organizations FROM anon, authenticated;
REVOKE ALL ON TABLE public.organization_memberships FROM anon, authenticated;
REVOKE ALL ON TABLE public.family_relationships FROM anon, authenticated;
REVOKE ALL ON TABLE public.platform_administrators FROM anon, authenticated;
REVOKE ALL ON TABLE public.audit_logs FROM anon, authenticated;

GRANT SELECT, UPDATE ON TABLE public.organizations TO authenticated;
GRANT SELECT ON TABLE public.organization_memberships TO authenticated;
GRANT SELECT ON TABLE public.family_relationships TO authenticated;

CREATE POLICY "organizations_read_for_members"
  ON public.organizations
  FOR SELECT
  TO authenticated
  USING (
    private.is_organization_member(id)
    OR private.is_platform_administrator()
  );

CREATE POLICY "organizations_update_for_administrators"
  ON public.organizations
  FOR UPDATE
  TO authenticated
  USING (
    private.has_organization_role(id, ARRAY['owner', 'admin', 'technician'])
    OR private.is_platform_administrator()
  )
  WITH CHECK (
    private.has_organization_role(id, ARRAY['owner', 'admin', 'technician'])
    OR private.is_platform_administrator()
  );

CREATE POLICY "memberships_read_own_or_administrated_organization"
  ON public.organization_memberships
  FOR SELECT
  TO authenticated
  USING (
    user_id = (SELECT auth.uid())
    OR private.has_organization_role(
      organization_id,
      ARRAY['owner', 'admin', 'technician', 'pedagogical_manager']
    )
    OR private.is_platform_administrator()
  );

CREATE POLICY "family_relationships_read_involved_or_staff"
  ON public.family_relationships
  FOR SELECT
  TO authenticated
  USING (
    parent_user_id = (SELECT auth.uid())
    OR learner_user_id = (SELECT auth.uid())
    OR private.has_organization_role(
      organization_id,
      ARRAY['owner', 'admin', 'technician', 'pedagogical_manager', 'teacher', 'class_manager']
    )
    OR private.is_platform_administrator()
  );

-- Profiles contain identity information, never authorization. Users can update
-- only explicitly safe columns; organization roles are stored separately.
REVOKE ALL ON TABLE public.profiles FROM anon, authenticated;
GRANT SELECT ON TABLE public.profiles TO authenticated;
GRANT UPDATE (full_name, preferred_name, avatar_url, locale, phone, updated_at)
  ON TABLE public.profiles TO authenticated;

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;

CREATE POLICY "profiles_read_own_or_linked_family"
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING (
    id = (SELECT auth.uid())
    OR EXISTS (
      SELECT 1
      FROM public.family_relationships AS relationship
      WHERE relationship.parent_user_id = (SELECT auth.uid())
        AND relationship.learner_user_id = profiles.id
        AND relationship.status = 'active'
    )
  );

CREATE POLICY "profiles_update_safe_own_fields"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (id = (SELECT auth.uid()))
  WITH CHECK (id = (SELECT auth.uid()));

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

CREATE OR REPLACE FUNCTION private.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', split_part(NEW.email, '@', 1))
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.handle_new_user() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION private.handle_new_user();

-- Tenant-scope the legacy learning tables. Their fuller replacement arrives in
-- the pedagogical foundation, but no cross-organization access is permitted now.
ALTER TABLE public.lessons
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.progress
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.quiz_results
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.homework_submissions
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.cohorts
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.regularity_score
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS lessons_organization_idx ON public.lessons (organization_id);
CREATE INDEX IF NOT EXISTS progress_organization_user_idx ON public.progress (organization_id, user_id);
CREATE INDEX IF NOT EXISTS quiz_results_organization_user_idx ON public.quiz_results (organization_id, user_id);
CREATE INDEX IF NOT EXISTS homework_organization_user_idx ON public.homework_submissions (organization_id, user_id);
CREATE INDEX IF NOT EXISTS cohorts_organization_idx ON public.cohorts (organization_id);
CREATE INDEX IF NOT EXISTS attendance_organization_user_idx ON public.attendance (organization_id, user_id);

DROP POLICY IF EXISTS "lessons_read_all" ON public.lessons;
DROP POLICY IF EXISTS "progress_own" ON public.progress;
DROP POLICY IF EXISTS "quiz_results_own" ON public.quiz_results;
DROP POLICY IF EXISTS "homework_own" ON public.homework_submissions;
DROP POLICY IF EXISTS "cohorts_read_auth" ON public.cohorts;
DROP POLICY IF EXISTS "attendance_own" ON public.attendance;
DROP POLICY IF EXISTS "regularity_own" ON public.regularity_score;

REVOKE ALL ON TABLE public.lessons FROM anon, authenticated;
REVOKE ALL ON TABLE public.progress FROM anon, authenticated;
REVOKE ALL ON TABLE public.quiz_results FROM anon, authenticated;
REVOKE ALL ON TABLE public.homework_submissions FROM anon, authenticated;
REVOKE ALL ON TABLE public.cohorts FROM anon, authenticated;
REVOKE ALL ON TABLE public.attendance FROM anon, authenticated;
REVOKE ALL ON TABLE public.regularity_score FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.lessons TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.progress TO authenticated;
GRANT SELECT, INSERT ON TABLE public.quiz_results TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.homework_submissions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.cohorts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.attendance TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.regularity_score TO authenticated;

CREATE POLICY "lessons_read_for_organization_members"
  ON public.lessons FOR SELECT TO authenticated
  USING (private.is_organization_member(organization_id));
CREATE POLICY "lessons_manage_for_teaching_staff"
  ON public.lessons FOR ALL TO authenticated
  USING (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'technician', 'pedagogical_manager', 'teacher']
  ))
  WITH CHECK (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'technician', 'pedagogical_manager', 'teacher']
  ));

CREATE POLICY "progress_read_own_or_staff"
  ON public.progress FOR SELECT TO authenticated
  USING (
    private.is_organization_member(organization_id)
    AND (
      user_id = (SELECT auth.uid())
      OR private.has_organization_role(
        organization_id,
        ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
      )
      OR private.is_linked_parent(organization_id, user_id)
    )
  );
CREATE POLICY "progress_write_own"
  ON public.progress FOR INSERT TO authenticated
  WITH CHECK (
    user_id = (SELECT auth.uid())
    AND private.has_organization_role(organization_id, ARRAY['learner'])
  );
CREATE POLICY "progress_update_own"
  ON public.progress FOR UPDATE TO authenticated
  USING (user_id = (SELECT auth.uid()) AND private.is_organization_member(organization_id))
  WITH CHECK (user_id = (SELECT auth.uid()) AND private.is_organization_member(organization_id));

CREATE POLICY "quiz_results_read_own_or_staff"
  ON public.quiz_results FOR SELECT TO authenticated
  USING (
    private.is_organization_member(organization_id)
    AND (
      user_id = (SELECT auth.uid())
      OR private.has_organization_role(
        organization_id,
        ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
      )
      OR private.is_linked_parent(organization_id, user_id)
    )
  );
CREATE POLICY "quiz_results_insert_own"
  ON public.quiz_results FOR INSERT TO authenticated
  WITH CHECK (
    user_id = (SELECT auth.uid())
    AND private.has_organization_role(organization_id, ARRAY['learner'])
  );

CREATE POLICY "homework_read_own_or_staff"
  ON public.homework_submissions FOR SELECT TO authenticated
  USING (
    private.is_organization_member(organization_id)
    AND (
      user_id = (SELECT auth.uid())
      OR private.has_organization_role(
        organization_id,
        ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
      )
      OR private.is_linked_parent(organization_id, user_id)
    )
  );
CREATE POLICY "homework_insert_own"
  ON public.homework_submissions FOR INSERT TO authenticated
  WITH CHECK (
    user_id = (SELECT auth.uid())
    AND private.has_organization_role(organization_id, ARRAY['learner'])
  );
CREATE POLICY "homework_update_own_or_staff"
  ON public.homework_submissions FOR UPDATE TO authenticated
  USING (
    private.has_organization_role(
      organization_id,
      ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
    )
  )
  WITH CHECK (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ));

CREATE POLICY "cohorts_read_for_organization_members"
  ON public.cohorts FOR SELECT TO authenticated
  USING (private.is_organization_member(organization_id));
CREATE POLICY "cohorts_manage_for_staff"
  ON public.cohorts FOR ALL TO authenticated
  USING (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'technician', 'pedagogical_manager', 'teacher']
  ))
  WITH CHECK (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'technician', 'pedagogical_manager', 'teacher']
  ));

CREATE POLICY "attendance_read_own_or_staff"
  ON public.attendance FOR SELECT TO authenticated
  USING (
    private.is_organization_member(organization_id)
    AND (
      user_id = (SELECT auth.uid())
      OR private.has_organization_role(
        organization_id,
        ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
      )
      OR private.is_linked_parent(organization_id, user_id)
    )
  );
CREATE POLICY "attendance_manage_for_staff"
  ON public.attendance FOR INSERT TO authenticated
  WITH CHECK (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ));
CREATE POLICY "attendance_update_for_staff"
  ON public.attendance FOR UPDATE TO authenticated
  USING (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ))
  WITH CHECK (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ));
CREATE POLICY "attendance_delete_for_staff"
  ON public.attendance FOR DELETE TO authenticated
  USING (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ));

CREATE POLICY "regularity_read_own_or_staff"
  ON public.regularity_score FOR SELECT TO authenticated
  USING (
    private.is_organization_member(organization_id)
    AND (
      user_id = (SELECT auth.uid())
      OR private.has_organization_role(
        organization_id,
        ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
      )
      OR private.is_linked_parent(organization_id, user_id)
    )
  );
CREATE POLICY "regularity_manage_for_staff"
  ON public.regularity_score FOR INSERT TO authenticated
  WITH CHECK (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ));
CREATE POLICY "regularity_update_for_staff"
  ON public.regularity_score FOR UPDATE TO authenticated
  USING (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ))
  WITH CHECK (private.has_organization_role(
    organization_id,
    ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
  ));

-- Homework objects use: <organization_id>/<learner_user_id>/<file>.
INSERT INTO storage.buckets (id, name, public)
VALUES ('homework', 'homework', false)
ON CONFLICT (id) DO UPDATE SET public = false;

CREATE OR REPLACE FUNCTION private.homework_object_organization_id(p_name text)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE
SET search_path = ''
AS $$
BEGIN
  RETURN (storage.foldername(p_name))[1]::uuid;
EXCEPTION WHEN invalid_text_representation OR array_subscript_error THEN
  RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION private.homework_object_organization_id(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION private.homework_object_organization_id(text) TO authenticated;

DROP POLICY IF EXISTS "homework_read_own" ON storage.objects;
DROP POLICY IF EXISTS "homework_insert_own" ON storage.objects;
DROP POLICY IF EXISTS "homework_update_own" ON storage.objects;
DROP POLICY IF EXISTS "homework_delete_own" ON storage.objects;
DROP POLICY IF EXISTS "homework_objects_read" ON storage.objects;
DROP POLICY IF EXISTS "homework_objects_insert" ON storage.objects;
DROP POLICY IF EXISTS "homework_objects_update" ON storage.objects;
DROP POLICY IF EXISTS "homework_objects_delete" ON storage.objects;

CREATE POLICY "homework_objects_read"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'homework'
    AND (
      (
        owner_id = (SELECT auth.uid()::text)
        AND (storage.foldername(name))[2] = (SELECT auth.uid()::text)
      )
      OR private.has_organization_role(
        private.homework_object_organization_id(name),
        ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher', 'class_manager']
      )
    )
  );

CREATE POLICY "homework_objects_insert"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'homework'
    AND owner_id = (SELECT auth.uid()::text)
    AND (storage.foldername(name))[2] = (SELECT auth.uid()::text)
    AND private.has_organization_role(
      private.homework_object_organization_id(name),
      ARRAY['learner']
    )
  );

CREATE POLICY "homework_objects_update"
  ON storage.objects FOR UPDATE TO authenticated
  USING (
    bucket_id = 'homework'
    AND owner_id = (SELECT auth.uid()::text)
    AND (storage.foldername(name))[2] = (SELECT auth.uid()::text)
  )
  WITH CHECK (
    bucket_id = 'homework'
    AND owner_id = (SELECT auth.uid()::text)
    AND (storage.foldername(name))[2] = (SELECT auth.uid()::text)
    AND private.has_organization_role(
      private.homework_object_organization_id(name),
      ARRAY['learner']
    )
  );

CREATE POLICY "homework_objects_delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'homework'
    AND (
      (
        owner_id = (SELECT auth.uid()::text)
        AND (storage.foldername(name))[2] = (SELECT auth.uid()::text)
      )
      OR private.has_organization_role(
        private.homework_object_organization_id(name),
        ARRAY['owner', 'admin', 'pedagogical_manager', 'teacher']
      )
    )
  );
