-- Sprint 4: lightweight admission CRM. Existing public applications are
-- preserved and moved into the expanded twelve-step workflow.

alter table public.organization_memberships
  drop constraint organization_memberships_role_check;
alter table public.organization_memberships
  add constraint organization_memberships_role_check check (role in (
    'owner', 'admin', 'technician', 'commercial', 'accounting', 'support',
    'pedagogical_manager', 'teacher', 'class_manager', 'parent', 'learner'
  ));

alter table public.organization_invitations
  drop constraint organization_invitations_role_check;
alter table public.organization_invitations
  add constraint organization_invitations_role_check check (role in (
    'admin', 'technician', 'commercial', 'accounting', 'support',
    'pedagogical_manager', 'teacher', 'class_manager', 'parent', 'learner'
  ));

alter table public.enrollment_applications
  drop constraint enrollment_applications_status_check;

update public.enrollment_applications set status = case status
  when 'qualified' then 'class_to_propose'
  when 'cohort_proposed' then 'proposal_sent'
  when 'declined' then 'closed'
  when 'withdrawn' then 'closed'
  else status
end;

alter table public.enrollment_applications
  add constraint enrollment_applications_status_check check (status in (
    'new', 'to_contact', 'contacted', 'needs_qualification',
    'assessment_required', 'class_to_propose', 'proposal_sent',
    'payment_pending', 'confirmed', 'access_sent',
    'first_login_check', 'closed'
  )),
  add column next_action text,
  add column follow_up_at timestamptz,
  add column internal_notes text,
  add column source_detail text,
  add column proposed_cohort_id uuid references public.cohorts(id) on delete set null,
  add column priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  add column payment_status text not null default 'not_requested'
    check (payment_status in ('not_requested', 'requested', 'partial', 'paid', 'cancelled', 'refunded')),
  add column close_outcome text check (
    close_outcome is null or close_outcome in ('refused', 'withdrawn', 'postponed')
  ),
  add column close_reason text,
  add column postponed_until date,
  add column learner_birth_date date,
  add column linked_user_id uuid references auth.users(id) on delete set null,
  add column linked_learner_id uuid references public.learner_profiles(id) on delete set null,
  add column access_sent_at timestamptz,
  add column first_login_verified_at timestamptz,
  add column first_contacted_at timestamptz,
  add column consent_at timestamptz,
  add column retained_until date,
  add column imported_batch_id uuid,
  add constraint enrollment_applications_internal_notes_length check (
    internal_notes is null or char_length(internal_notes) <= 10000
  ),
  add constraint enrollment_applications_next_action_length check (
    next_action is null or char_length(next_action) <= 300
  );

update public.enrollment_applications
set consent_at = created_at,
    retained_until = (created_at + interval '3 years')::date,
    close_outcome = case when status = 'closed' then 'withdrawn' else close_outcome end,
    close_reason = case when status = 'closed' then coalesce(close_reason, 'Historique migré') else close_reason end;

alter table public.enrollment_applications
  add constraint enrollment_applications_close_reason_required check (
    status <> 'closed' or (close_outcome is not null and nullif(btrim(close_reason), '') is not null)
  );

create index enrollment_applications_work_queue_idx
  on public.enrollment_applications (organization_id, status, priority, follow_up_at, created_at desc);
create index enrollment_applications_unassigned_idx
  on public.enrollment_applications (organization_id, created_at desc)
  where assigned_to is null and status <> 'closed';
create index enrollment_applications_follow_up_idx
  on public.enrollment_applications (organization_id, follow_up_at)
  where follow_up_at is not null and status <> 'closed';
create index enrollment_applications_proposed_cohort_idx
  on public.enrollment_applications (proposed_cohort_id);
create index enrollment_applications_email_normalized_idx
  on public.enrollment_applications (organization_id, lower(email), created_at desc);
create index enrollment_applications_phone_normalized_idx
  on public.enrollment_applications (organization_id, regexp_replace(phone, '[^0-9+]', '', 'g'));
create index enrollment_applications_first_login_idx
  on public.enrollment_applications (organization_id, access_sent_at)
  where status in ('access_sent', 'first_login_check') and first_login_verified_at is null;

create table public.admission_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  application_id uuid not null references public.enrollment_applications(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in (
    'created', 'stage_changed', 'assigned', 'follow_up_scheduled', 'note_added',
    'class_proposed', 'waitlisted', 'payment_changed', 'account_linked',
    'learner_enrolled', 'access_sent', 'first_login_verified', 'closed',
    'bulk_action', 'imported'
  )),
  summary text not null check (char_length(summary) between 2 and 500),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index admission_events_application_created_idx
  on public.admission_events (application_id, created_at desc);
create index admission_events_organization_created_idx
  on public.admission_events (organization_id, created_at desc);

create table public.admission_payments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  application_id uuid not null references public.enrollment_applications(id) on delete cascade,
  learner_id uuid references public.learner_profiles(id) on delete set null,
  cohort_id uuid references public.cohorts(id) on delete set null,
  expected_amount_cents integer not null default 0 check (expected_amount_cents >= 0),
  received_amount_cents integer not null default 0 check (received_amount_cents >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  due_on date,
  payment_method text check (payment_method is null or payment_method in (
    'cash', 'bank_transfer', 'cheque', 'card_external', 'other'
  )),
  payment_reference text,
  status text not null default 'not_requested' check (status in (
    'not_requested', 'requested', 'partial', 'paid', 'cancelled', 'refunded'
  )),
  stripe_payment_id text,
  internal_notes text,
  validated_by uuid references auth.users(id) on delete set null,
  validated_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (application_id, cohort_id),
  check (received_amount_cents <= expected_amount_cents or status = 'refunded')
);
create index admission_payments_queue_idx
  on public.admission_payments (organization_id, status, due_on);
create index admission_payments_learner_idx on public.admission_payments (learner_id);
create index admission_payments_cohort_idx on public.admission_payments (cohort_id);
create index admission_payments_validated_by_idx on public.admission_payments (validated_by);
create index admission_payments_created_by_idx on public.admission_payments (created_by);

create table public.admission_message_templates (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  template_key text not null check (template_key in (
    'acknowledgement', 'missing_information', 'class_proposal', 'assessment_invitation',
    'payment_reminder', 'enrollment_confirmation', 'access_sent',
    'first_login_reminder', 'waitlist', 'refusal_or_postponement'
  )),
  locale text not null default 'fr',
  title text not null,
  body text not null check (char_length(body) between 2 and 4000),
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, template_key, locale)
);
create index admission_message_templates_created_by_idx
  on public.admission_message_templates (created_by);

create table public.admission_saved_filters (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  filters jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, user_id, name)
);
create index admission_saved_filters_user_idx
  on public.admission_saved_filters (user_id, updated_at desc);

create table public.admission_import_batches (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  file_name text not null,
  status text not null default 'previewed' check (status in ('previewed', 'imported', 'cancelled')),
  total_rows integer not null default 0 check (total_rows >= 0),
  imported_rows integer not null default 0 check (imported_rows >= 0),
  duplicate_rows integer not null default 0 check (duplicate_rows >= 0),
  error_rows integer not null default 0 check (error_rows >= 0),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create index admission_import_batches_org_created_idx
  on public.admission_import_batches (organization_id, created_at desc);
create index admission_import_batches_created_by_idx
  on public.admission_import_batches (created_by);

alter table public.enrollment_applications
  add constraint enrollment_applications_imported_batch_fkey
  foreign key (imported_batch_id) references public.admission_import_batches(id) on delete set null;

create or replace function private.can_read_admissions(p_organization_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_organization_role(p_organization_id, array[
    'owner','admin','commercial','class_manager','pedagogical_manager','accounting','support','technician'
  ]) or private.is_platform_administrator();
$$;
create or replace function private.can_manage_admissions(p_organization_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_organization_role(p_organization_id, array[
    'owner','admin','commercial','class_manager'
  ]) or private.is_platform_administrator();
$$;
create or replace function private.can_manage_admission_finance(p_organization_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_organization_role(p_organization_id, array['owner','admin','accounting'])
    or private.is_platform_administrator();
$$;
create or replace function private.can_manage_admission_templates(p_organization_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.has_organization_role(p_organization_id, array['owner','admin'])
    or private.is_platform_administrator();
$$;

revoke all on function private.can_read_admissions(uuid) from public, anon;
revoke all on function private.can_manage_admissions(uuid) from public, anon;
revoke all on function private.can_manage_admission_finance(uuid) from public, anon;
revoke all on function private.can_manage_admission_templates(uuid) from public, anon;
grant execute on function private.can_read_admissions(uuid) to authenticated;
grant execute on function private.can_manage_admissions(uuid) to authenticated;
grant execute on function private.can_manage_admission_finance(uuid) to authenticated;
grant execute on function private.can_manage_admission_templates(uuid) to authenticated;

create or replace function private.guard_admission_application_update()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare
  v_direction boolean := private.has_organization_role(old.organization_id, array['owner','admin'])
    or private.is_platform_administrator();
  v_commercial boolean := private.has_organization_role(old.organization_id, array['commercial']);
  v_classes boolean := private.has_organization_role(old.organization_id, array['class_manager']);
  v_pedagogy boolean := private.has_organization_role(old.organization_id, array['pedagogical_manager']);
  v_support boolean := private.has_organization_role(old.organization_id, array['support','technician']);
begin
  if current_user in ('postgres', 'service_role') or pg_trigger_depth() > 1 then return new; end if;
  if new.organization_id is distinct from old.organization_id
    or new.email is distinct from old.email
    or new.privacy_consent is distinct from old.privacy_consent then
    raise exception 'Les données d’origine de la demande ne peuvent pas être déplacées ou remplacées.';
  end if;
  if v_direction then return new; end if;
  if v_commercial and
    (to_jsonb(new) - array[
      'audience','objective','level','availability','accompaniment_language','applicant_name',
      'learner_name','phone','preferred_contact','notes','source','cohort_id','assigned_to',
      'status','next_action','follow_up_at','internal_notes','source_detail','proposed_cohort_id',
      'priority','close_outcome','close_reason','postponed_until','learner_birth_date',
      'first_contacted_at','updated_at'
    ]::text[]) =
    (to_jsonb(old) - array[
      'audience','objective','level','availability','accompaniment_language','applicant_name',
      'learner_name','phone','preferred_contact','notes','source','cohort_id','assigned_to',
      'status','next_action','follow_up_at','internal_notes','source_detail','proposed_cohort_id',
      'priority','close_outcome','close_reason','postponed_until','learner_birth_date',
      'first_contacted_at','updated_at'
    ]::text[]) then return new; end if;
  if v_classes and
    (to_jsonb(new) - array['proposed_cohort_id','status','next_action','follow_up_at','internal_notes','priority','updated_at']::text[]) =
    (to_jsonb(old) - array['proposed_cohort_id','status','next_action','follow_up_at','internal_notes','priority','updated_at']::text[])
    then return new; end if;
  if v_pedagogy and
    (to_jsonb(new) - array['objective','level','status','next_action','follow_up_at','internal_notes','updated_at']::text[]) =
    (to_jsonb(old) - array['objective','level','status','next_action','follow_up_at','internal_notes','updated_at']::text[])
    then return new; end if;
  if v_support and
    (to_jsonb(new) - array['next_action','follow_up_at','internal_notes','first_login_verified_at','updated_at']::text[]) =
    (to_jsonb(old) - array['next_action','follow_up_at','internal_notes','first_login_verified_at','updated_at']::text[])
    then return new; end if;
  raise exception 'Votre rôle ne permet pas cette modification.';
end;
$$;
revoke all on function private.guard_admission_application_update() from public, anon, authenticated;

create trigger enrollment_applications_guard_update
before update on public.enrollment_applications
for each row execute function private.guard_admission_application_update();

create or replace function private.prevent_recent_duplicate_application()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if exists (
    select 1
    from public.enrollment_applications existing
    where existing.organization_id = new.organization_id
      and existing.created_at >= now() - interval '24 hours'
      and existing.status <> 'closed'
      and lower(btrim(existing.email)) = lower(btrim(new.email))
      and lower(btrim(existing.learner_name)) = lower(btrim(new.learner_name))
  ) then
    raise exception using
      errcode = '23505',
      message = 'Une demande récente existe déjà pour cet élève.',
      hint = 'Retrouvez la demande existante ou réessayez après 24 heures.';
  end if;
  return new;
end;
$$;
revoke all on function private.prevent_recent_duplicate_application() from public, anon, authenticated;
create trigger enrollment_applications_prevent_recent_duplicate
before insert on public.enrollment_applications
for each row execute function private.prevent_recent_duplicate_application();

create or replace function private.log_admission_application_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_type text; v_summary text;
begin
  if new.status is distinct from old.status then
    v_type := case when new.status='closed' then 'closed' else 'stage_changed' end;
    v_summary := 'Étape : ' || old.status || ' → ' || new.status;
  elsif new.assigned_to is distinct from old.assigned_to then
    v_type := 'assigned'; v_summary := 'Responsable modifié';
  elsif new.proposed_cohort_id is distinct from old.proposed_cohort_id then
    v_type := 'class_proposed'; v_summary := 'Classe proposée modifiée';
  elsif new.follow_up_at is distinct from old.follow_up_at then
    v_type := 'follow_up_scheduled'; v_summary := 'Relance programmée';
  elsif new.first_login_verified_at is distinct from old.first_login_verified_at then
    v_type := 'first_login_verified'; v_summary := 'Première connexion vérifiée';
  else return new;
  end if;
  insert into public.admission_events(
    organization_id, application_id, actor_user_id, event_type, summary, metadata
  ) values (
    new.organization_id, new.id, auth.uid(), v_type, v_summary,
    jsonb_build_object('old_status',old.status,'new_status',new.status)
  );
  return new;
end;
$$;
revoke all on function private.log_admission_application_change() from public, anon, authenticated;
create trigger enrollment_applications_log_change
after update on public.enrollment_applications
for each row execute function private.log_admission_application_change();

create or replace function private.sync_application_payment_status()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  update public.enrollment_applications
  set payment_status = new.status, updated_at = now()
  where id = new.application_id;
  insert into public.admission_events(
    organization_id, application_id, actor_user_id, event_type, summary, metadata
  ) values (
    new.organization_id, new.application_id, auth.uid(), 'payment_changed',
    'Paiement : ' || coalesce(old.status, '—') || ' → ' || new.status,
    jsonb_build_object('payment_id',new.id,'expected_amount_cents',new.expected_amount_cents,'received_amount_cents',new.received_amount_cents)
  );
  return new;
end;
$$;
revoke all on function private.sync_application_payment_status() from public, anon, authenticated;
create trigger admission_payments_sync_application
after insert or update on public.admission_payments
for each row execute function private.sync_application_payment_status();

alter table public.admission_events enable row level security;
alter table public.admission_payments enable row level security;
alter table public.admission_message_templates enable row level security;
alter table public.admission_saved_filters enable row level security;
alter table public.admission_import_batches enable row level security;

revoke all on public.admission_events, public.admission_payments,
  public.admission_message_templates, public.admission_saved_filters,
  public.admission_import_batches from anon, authenticated;
grant select, insert on public.admission_events to authenticated;
grant select, insert, update on public.admission_payments to authenticated;
grant select, insert, update on public.admission_message_templates to authenticated;
grant select, insert, update, delete on public.admission_saved_filters to authenticated;
grant select, insert, update on public.admission_import_batches to authenticated;

drop policy enrollment_applications_staff_read on public.enrollment_applications;
drop policy enrollment_applications_staff_update on public.enrollment_applications;
create policy enrollment_applications_admission_read on public.enrollment_applications
for select to authenticated using (
  private.can_read_admissions(organization_id)
  and (
    not private.has_organization_role(organization_id, array['support','technician'])
    or status in ('access_sent','first_login_check')
    or private.has_organization_role(organization_id, array['owner','admin'])
  )
);
create policy enrollment_applications_admission_update on public.enrollment_applications
for update to authenticated using (private.can_read_admissions(organization_id))
with check (private.can_read_admissions(organization_id));

create policy admission_events_read on public.admission_events for select to authenticated
using (private.can_read_admissions(organization_id));
create policy admission_events_insert on public.admission_events for insert to authenticated
with check (
  private.can_read_admissions(organization_id)
  and actor_user_id = auth.uid()
  and event_type in ('note_added','bulk_action')
);

create policy admission_payments_read on public.admission_payments for select to authenticated
using (
  private.can_manage_admission_finance(organization_id)
  or private.has_organization_role(organization_id, array['commercial','class_manager'])
);
create policy admission_payments_insert on public.admission_payments for insert to authenticated
with check (private.can_manage_admission_finance(organization_id) and created_by=auth.uid());
create policy admission_payments_update on public.admission_payments for update to authenticated
using (private.can_manage_admission_finance(organization_id))
with check (private.can_manage_admission_finance(organization_id));

create policy admission_templates_read on public.admission_message_templates for select to authenticated
using (private.can_read_admissions(organization_id));
create policy admission_templates_insert on public.admission_message_templates for insert to authenticated
with check (private.can_manage_admission_templates(organization_id));
create policy admission_templates_update on public.admission_message_templates for update to authenticated
using (private.can_manage_admission_templates(organization_id))
with check (private.can_manage_admission_templates(organization_id));

create policy admission_saved_filters_all on public.admission_saved_filters for all to authenticated
using (user_id=auth.uid() and private.can_read_admissions(organization_id))
with check (user_id=auth.uid() and private.can_read_admissions(organization_id));

create policy admission_imports_read on public.admission_import_batches for select to authenticated
using (private.can_manage_admissions(organization_id));
create policy admission_imports_insert on public.admission_import_batches for insert to authenticated
with check (private.can_manage_admissions(organization_id) and created_by=auth.uid());
create policy admission_imports_update on public.admission_import_batches for update to authenticated
using (private.can_manage_admissions(organization_id))
with check (private.can_manage_admissions(organization_id));

insert into public.admission_events(organization_id,application_id,event_type,summary,metadata,created_at)
select organization_id,id,'created','Demande reçue',jsonb_build_object('source',source),created_at
from public.enrollment_applications
where not exists (select 1 from public.admission_events e where e.application_id=enrollment_applications.id);

insert into public.admission_message_templates(organization_id,template_key,locale,title,body)
select o.id, t.template_key, 'fr', t.title, t.body
from public.organizations o
cross join (values
  ('acknowledgement','Demande reçue','Bonjour {{prenom}}, nous avons bien reçu votre demande. Notre équipe revient vers vous rapidement.'),
  ('missing_information','Informations complémentaires','Bonjour {{prenom}}, afin de vous orienter vers la bonne classe, pouvez-vous nous préciser : {{informations}} ?'),
  ('class_proposal','Proposition de classe','Bonjour {{prenom}}, nous vous proposons la classe {{classe}}, prévue {{creneau}}. Souhaitez-vous confirmer cette proposition ?'),
  ('assessment_invitation','Évaluation de niveau','Bonjour {{prenom}}, nous vous proposons une courte évaluation le {{date}} afin de confirmer le niveau adapté.'),
  ('payment_reminder','Rappel de paiement','Bonjour {{prenom}}, votre inscription à la classe {{classe}} reste en attente du règlement de {{montant}}.'),
  ('enrollment_confirmation','Inscription confirmée','Bonjour {{prenom}}, votre inscription à la classe {{classe}} est confirmée.'),
  ('access_sent','Accès envoyé','Bonjour {{prenom}}, votre accès Diakspora Karanta vient de vous être envoyé par e-mail.'),
  ('first_login_reminder','Première connexion','Bonjour {{prenom}}, avez-vous pu ouvrir votre accès Diakspora Karanta ? Nous pouvons vous aider si besoin.'),
  ('waitlist','Liste d’attente','Bonjour {{prenom}}, la classe souhaitée est complète. Nous vous avons placé sur liste d’attente et reviendrons vers vous dès qu’une place se libère.'),
  ('refusal_or_postponement','Suite de votre demande','Bonjour {{prenom}}, votre demande est actuellement {{decision}}. Vous pourrez reprendre contact avec nous lorsque vous le souhaitez.')
) as t(template_key,title,body)
on conflict (organization_id,template_key,locale) do nothing;

create or replace function public.recommend_classes_for_application(p_application_id uuid)
returns table(
  cohort_id uuid, cohort_name text, score integer, recommended boolean,
  reasons text[], exclusions text[], remaining_places integer, availability text
)
language sql stable security invoker set search_path = '' as $$
  with application as (
    select * from public.enrollment_applications a
    where a.id=p_application_id and private.can_read_admissions(a.organization_id)
  ), candidates as (
    select c.*, a.audience requested_audience, a.objective requested_objective,
      a.level requested_level, a.availability requested_availability,
      a.accompaniment_language requested_language, a.learner_birth_date,
      case when a.learner_birth_date is null then null
        else extract(year from age(current_date, a.learner_birth_date))::integer end requested_age,
      (select count(*) from public.learner_cohort_memberships m where m.cohort_id=c.id and m.status='active') active_count
    from public.cohorts c join application a on a.organization_id=c.organization_id
    where c.status='active'
  )
  select c.id, c.name,
    (case when c.audience=c.requested_audience then 35 else 0 end
      + case when c.objective=c.requested_objective then 25 else 0 end
      + case when c.requested_level='unsure' or c.level=c.requested_level then 15 else 0 end
      + case when c.session_period=c.requested_availability or c.delivery_format='on_demand' then 10 else 0 end
      + case when c.requested_language=any(c.teaching_languages) then 10 else 0 end
      + case when c.requested_age is null
          or ((c.age_min is null or c.requested_age>=c.age_min) and (c.age_max is null or c.requested_age<=c.age_max))
        then 5 else 0 end
      + case when c.enrollment_status='open' and (c.max_students is null or c.active_count<c.max_students) then 5 else 0 end)::integer score,
    (c.audience=c.requested_audience and c.objective=c.requested_objective
      and (c.requested_level='unsure' or c.level=c.requested_level)
      and c.enrollment_status in ('open','waitlist')
      and (c.starts_on is null or c.ends_on is null or c.ends_on>=current_date)
      and (c.requested_age is null or ((c.age_min is null or c.requested_age>=c.age_min) and (c.age_max is null or c.requested_age<=c.age_max)))
      and (c.max_students is null or c.active_count<c.max_students or c.enrollment_status='waitlist')) recommended,
    array_remove(array[
      case when c.audience=c.requested_audience then 'Public et règle de mixité compatibles' end,
      case when c.objective=c.requested_objective then 'Objectif pédagogique compatible' end,
      case when c.requested_level='unsure' or c.level=c.requested_level then 'Niveau compatible' end,
      case when c.session_period=c.requested_availability or c.delivery_format='on_demand' then 'Disponibilité compatible' end,
      case when c.requested_language=any(c.teaching_languages) then 'Langue compatible' end
      ,case when c.requested_age is null then 'Âge à confirmer'
        when (c.age_min is null or c.requested_age>=c.age_min) and (c.age_max is null or c.requested_age<=c.age_max)
        then 'Tranche d’âge compatible' end
    ],null),
    array_remove(array[
      case when c.audience<>c.requested_audience then 'Public ou règle de mixité incompatible' end,
      case when c.objective<>c.requested_objective then 'Objectif différent' end,
      case when c.requested_level<>'unsure' and c.level is distinct from c.requested_level then 'Niveau différent' end,
      case when c.session_period is distinct from c.requested_availability and c.delivery_format<>'on_demand' then 'Créneau différent' end,
      case when not(c.requested_language=any(c.teaching_languages)) then 'Langue non proposée' end,
      case when c.requested_age is not null and not ((c.age_min is null or c.requested_age>=c.age_min) and (c.age_max is null or c.requested_age<=c.age_max)) then 'Tranche d’âge incompatible' end,
      case when c.enrollment_status='closed' then 'Inscriptions fermées' end,
      case when c.max_students is not null and c.active_count>=c.max_students then 'Classe complète' end,
      case when c.ends_on is not null and c.ends_on<current_date then 'Classe terminée' end
    ],null),
    case when c.max_students is null then null else greatest(c.max_students-c.active_count,0)::integer end,
    case when c.enrollment_status='closed' then 'closed'
      when c.max_students is not null and c.active_count>=c.max_students then 'full'
      else c.enrollment_status end
  from candidates c
  order by recommended desc, score desc, c.starts_on nulls last, c.name;
$$;
revoke all on function public.recommend_classes_for_application(uuid) from public, anon;
grant execute on function public.recommend_classes_for_application(uuid) to authenticated;

comment on table public.enrollment_applications is
  'Demandes d admission. Les demandes closes sont conservées trois ans par défaut puis doivent être anonymisées ou supprimées selon la politique de l organisation.';
comment on column public.enrollment_applications.retained_until is
  'Date de révision de conservation. Ne provoque aucune suppression automatique.';
